### ISSUE TITLE
Info in PHP Logs

### ISSUE THREAD

**Issue by DavideIadeluca** [imorland/html-head#3]
When viewing logs of the PHP container, the following info is printed (multiple times):

`flarum.INFO: [ianm/html-head] Cleared cache for active_html_headers due to Flarum\Foundation\Event\ClearingCache event firing.`

Is this expected?

**Comment by imorland** [comment]
This should only appear in `debug` mode, but I can see that it will log this every time the cache is cleared regardless of the debug status. Thanks for pointing this out, I'll address this shortly!
